name: PlatformIO CI

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build_examples:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - example: examples/simple
            boards: "--board=uno --board=teensy31 --board=esp32dev"
          - example: examples/a2dp_i2s
            lib-deps: "git+https://github.com/pschatzmann/ESP32-A2DP#v1.7.1"
            boards: "--board=esp32dev"
    steps:
    - uses: actions/checkout@v4
    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          ~/.platformio/.cache
        key: ${{ runner.os }}-pio
    - name: Setup Python
      uses: actions/setup-python@v5
    - name: Install PlatformIO
      run: pip install --upgrade platformio
    - name: Run PlatformIO
      run: pio ci --lib="." $BOARDS --project-option="lib_deps=$LIB_DEPS"
      env:
        PLATFORMIO_CI_SRC: ${{ matrix.example }}
        BOARDS: ${{ matrix.boards }}
        LIB_DEPS: ${{ matrix.lib-deps }}

  run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          ~/.platformio/.cache
        key: ${{ runner.os }}-pio
    - name: Setup Python
      uses: actions/setup-python@v5
    - name: Install PlatformIO
      run: pip install --upgrade platformio
    - name: Run PlatformIO
      run: pio test -e native -v --junit-output-path="test_log.xml"